# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Frontends Blog 
tagline:          'About our community'
description:      'About our community'
url:              http://blog.frontends.org
baseurl:          '/'
paginate:         5

author:
  name:           'Juan Olvera'
  url:            https://twitter.com/thinkxl

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
